export const DEFAULT_TOPICS: Record<"JAVA" | "DSA" | "APTITUDE", string[]> = {
  JAVA: [
    "Basics",
    "OOP",
    "Collections",
    "Exception Handling",
    "File Handling",
    "Generics",
    "Streams",
    "Lambda Expressions",
    "JDBC",
    "Multithreading",
    "Spring Boot",
    "REST APIs",
  ],
  DSA: [
    "Arrays",
    "Strings",
    "Searching",
    "Sorting",
    "HashMap & Sets",
    "Linked List",
    "Stack",
    "Queue",
    "Tree",
    "BST",
    "Heap",
    "Trie",
    "Graph",
    "Dynamic Programming",
    "Greedy",
    "Sliding Window",
    "Backtracking",
    "Recursion",
    "Bit Manipulation",
    "Math",
  ],
  APTITUDE: [
    "Percentages",
    "Profit & Loss",
    "Ratio & Proportion",
    "Probability",
    "Permutation",
    "Combination",
    "Time Speed Distance",
    "Time & Work",
    "Clock",
    "Calendar",
    "Pipes & Cisterns",
    "Blood Relation",
    "Direction Sense",
    "Coding Decoding",
    "Number Series",
    "Puzzles",
  ],
};

export const DEFAULT_COMPANIES = [
  "Zoho",
  "Amazon",
  "Microsoft",
  "Google",
  "Oracle",
  "Adobe",
  "Cisco",
  "TCS",
  "Infosys",
  "Accenture",
  "Capgemini",
];
